import type { FoodCommodity, PackagingMaterial, ReferenceSource } from './types';

/**
 * DEMO / REFERENCE DATASET — NOT laboratory-certified.
 * Indicative literature-style figures that make the decision-support models
 * runnable. Each value carries provenance 'reference' and points at a source
 * id in SOURCES. Real deployments should replace with verified measurements
 * (see VALIDATION.md).
 */

export const SOURCES: ReferenceSource[] = [
  {
    id: 'src-demo',
    title: 'NutriPack Demo Dataset',
    publisher: 'NutriPack (internal reference compilation)',
    year: 2026,
    notes:
      'Indicative reference figures compiled for demonstration and model operation. NOT laboratory-certified. Replace with verified data for production use.',
  },
  {
    id: 'src-postharvest',
    title: 'Postharvest Handling of Horticultural Crops — typical storage and respiration ranges',
    publisher: 'Textbook reference compilation',
    year: 2015,
    notes: 'Typical storage temperature/RH ranges and respiration classes for fresh produce (reference ranges, not measurements).',
  },
  {
    id: 'src-film-data',
    title: 'Plastic Film Technology — typical permeability ranges for packaging films',
    publisher: 'Textbook reference compilation',
    year: 2013,
    notes: 'Typical OTR/WVTR ranges for commodity films at standard test conditions; wide ranges, order-of-magnitude guidance.',
  },
  {
    id: 'src-lca',
    title: 'Simplified packaging LCA factors — cradle-to-gate estimates',
    publisher: 'NutriPack (simplified factors)',
    year: 2026,
    notes: 'Simplified cradle-to-gate CO2e factors per m² for comparative ranking only. Not an ISO-14040-conformant LCA.',
  },
];

const ref = (value: number, sourceId = 'src-demo') => ({ value, provenance: 'reference' as const, sourceId });

export const COMMODITIES: FoodCommodity[] = [
  // ——— Added for the Complete Packaging Solution upgrade (liquid/frozen coverage) ———
  {
    id: 'milk',
    name: 'Milk (pasteurized)',
    category: 'dairy',
    form: 'processed',
    typicalStorageEnv: 'refrigerated',
    storageTempRangeC: [0, 4],
    storageRhRangePct: [50, 90],
    indicativeShelfLifeDays: ref(3, 'src-demo'),
    properties: {
      moistureContentPct: 87,
      ph: 6.7,
      fatPct: 3.5,
      proteinPct: 3.3,
      waterActivity: 0.99,
      respirationRateMgCo2KgH: 0,
      oxygenSensitivity: 3,
      moistureSensitivity: 0,
      lightSensitivity: 4,
      temperatureSensitivity: 5,
    },
    valuePerKgInr: ref(60),
    notes: 'Liquid — leak-proof primary + cold chain mandatory; light damages riboflavin.',
    sourceIds: ['src-demo'],
  },
  {
    id: 'mustard-oil',
    name: 'Mustard oil (edible)',
    category: 'beverage',
    form: 'processed',
    typicalStorageEnv: 'ambient',
    storageTempRangeC: [10, 30],
    storageRhRangePct: [40, 70],
    indicativeShelfLifeDays: ref(270, 'src-demo'),
    properties: {
      moistureContentPct: 0.1,
      ph: 6,
      fatPct: 99.9,
      proteinPct: 0,
      waterActivity: 0.1,
      respirationRateMgCo2KgH: 0,
      oxygenSensitivity: 5,
      moistureSensitivity: 0,
      lightSensitivity: 4,
      temperatureSensitivity: 1,
    },
    valuePerKgInr: ref(180),
    notes: 'Fat-rich liquid: oxidation + light are the enemies; leak-proof bottle/tin with induction seal.',
    sourceIds: ['src-demo'],
  },
  {
    id: 'frozen-peas',
    name: 'Frozen green peas',
    category: 'vegetable',
    form: 'processed',
    typicalStorageEnv: 'frozen',
    storageTempRangeC: [-20, -15],
    storageRhRangePct: [40, 90],
    indicativeShelfLifeDays: ref(365, 'src-demo'),
    properties: {
      moistureContentPct: 70,
      ph: 6.8,
      fatPct: 0.4,
      proteinPct: 5,
      waterActivity: 0.95,
      respirationRateMgCo2KgH: 0,
      oxygenSensitivity: 2,
      moistureSensitivity: 2,
      lightSensitivity: 1,
      temperatureSensitivity: 5,
    },
    valuePerKgInr: ref(90),
    notes: 'Unbroken cold chain (−18 °C) is the shelf life; packaging needs freezer flexibility.',
    sourceIds: ['src-demo'],
  },
  {
    id: 'tomato',
    name: 'Tomato',
    category: 'vegetable',
    form: 'fresh',
    typicalStorageEnv: 'refrigerated',
    storageTempRangeC: [7, 12],
    storageRhRangePct: [85, 95],
    indicativeShelfLifeDays: ref(10, 'src-postharvest'),
    properties: {
      moistureContentPct: 94,
      ph: 4.3,
      fatPct: 0.2,
      proteinPct: 0.9,
      waterActivity: 0.99,
      respirationRateMgCo2KgH: 18,
      oxygenSensitivity: 2,
      moistureSensitivity: 3,
      lightSensitivity: 1,
      temperatureSensitivity: 4,
    },
    valuePerKgInr: ref(30),
    notes: 'High respiration climacteric fruit-vegetable; chilling injury below 7°C.',
    sourceIds: ['src-postharvest'],
  },
  {
    id: 'potato',
    name: 'Potato',
    category: 'vegetable',
    form: 'fresh',
    typicalStorageEnv: 'ambient',
    storageTempRangeC: [4, 10],
    storageRhRangePct: [85, 95],
    indicativeShelfLifeDays: ref(60, 'src-postharvest'),
    properties: {
      moistureContentPct: 79,
      ph: 5.9,
      fatPct: 0.1,
      proteinPct: 2.0,
      waterActivity: 0.98,
      respirationRateMgCo2KgH: 8,
      oxygenSensitivity: 1,
      moistureSensitivity: 2,
      lightSensitivity: 2,
      temperatureSensitivity: 2,
    },
    valuePerKgInr: ref(22),
    notes: 'Low respiration; light causes greening; needs vented packaging.',
    sourceIds: ['src-postharvest'],
  },
  {
    id: 'apple',
    name: 'Apple',
    category: 'fruit',
    form: 'fresh',
    typicalStorageEnv: 'refrigerated',
    storageTempRangeC: [0, 4],
    storageRhRangePct: [85, 95],
    indicativeShelfLifeDays: ref(40, 'src-postharvest'),
    properties: {
      moistureContentPct: 85,
      ph: 3.4,
      fatPct: 0.2,
      proteinPct: 0.3,
      waterActivity: 0.97,
      respirationRateMgCo2KgH: 8,
      oxygenSensitivity: 3,
      moistureSensitivity: 2,
      lightSensitivity: 0,
      temperatureSensitivity: 3,
    },
    valuePerKgInr: ref(90),
    notes: 'Moderate respiration; MAP with low O2 extends modelled shelf life.',
    sourceIds: ['src-postharvest'],
  },
  {
    id: 'mango',
    name: 'Mango',
    category: 'fruit',
    form: 'fresh',
    typicalStorageEnv: 'refrigerated',
    storageTempRangeC: [10, 13],
    storageRhRangePct: [85, 95],
    indicativeShelfLifeDays: ref(9, 'src-postharvest'),
    properties: {
      moistureContentPct: 83,
      ph: 3.9,
      fatPct: 0.4,
      proteinPct: 0.8,
      waterActivity: 0.98,
      respirationRateMgCo2KgH: 22,
      oxygenSensitivity: 3,
      moistureSensitivity: 3,
      lightSensitivity: 1,
      temperatureSensitivity: 5,
    },
    valuePerKgInr: ref(120),
    notes: 'Chilling-sensitive tropical fruit; cold-chain dependent.',
    sourceIds: ['src-postharvest'],
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'fruit',
    form: 'fresh',
    typicalStorageEnv: 'refrigerated',
    storageTempRangeC: [12, 15],
    storageRhRangePct: [85, 95],
    indicativeShelfLifeDays: ref(7, 'src-postharvest'),
    properties: {
      moistureContentPct: 75,
      ph: 4.7,
      fatPct: 0.3,
      proteinPct: 1.1,
      waterActivity: 0.97,
      respirationRateMgCo2KgH: 25,
      oxygenSensitivity: 3,
      moistureSensitivity: 2,
      lightSensitivity: 0,
      temperatureSensitivity: 5,
    },
    valuePerKgInr: ref(40),
    notes: 'High respiration; chilling injury below 12°C.',
    sourceIds: ['src-postharvest'],
  },
  {
    id: 'onion',
    name: 'Onion',
    category: 'vegetable',
    form: 'fresh',
    typicalStorageEnv: 'ambient',
    storageTempRangeC: [0, 25],
    storageRhRangePct: [60, 70],
    indicativeShelfLifeDays: ref(40, 'src-postharvest'),
    properties: {
      moistureContentPct: 86,
      ph: 5.4,
      fatPct: 0.1,
      proteinPct: 1.1,
      waterActivity: 0.97,
      respirationRateMgCo2KgH: 8,
      oxygenSensitivity: 1,
      moistureSensitivity: 3,
      lightSensitivity: 1,
      temperatureSensitivity: 2,
    },
    valuePerKgInr: ref(25),
    notes: 'Requires low humidity and ventilation; sprouting risk.',
    sourceIds: ['src-postharvest'],
  },
  {
    id: 'rice',
    name: 'Rice (milled)',
    category: 'cereal',
    form: 'processed',
    typicalStorageEnv: 'ambient',
    storageTempRangeC: [10, 30],
    storageRhRangePct: [50, 65],
    indicativeShelfLifeDays: ref(180, 'src-demo'),
    properties: {
      moistureContentPct: 12,
      ph: 6.5,
      fatPct: 0.8,
      proteinPct: 7,
      waterActivity: 0.6,
      oxygenSensitivity: 1,
      moistureSensitivity: 5,
      lightSensitivity: 1,
      temperatureSensitivity: 1,
    },
    valuePerKgInr: ref(45),
    notes: 'Shelf life governed by moisture and insect access; hermetic options exist.',
    sourceIds: ['src-demo'],
  },
  {
    id: 'wheat',
    name: 'Wheat grain',
    category: 'cereal',
    form: 'processed',
    typicalStorageEnv: 'ambient',
    storageTempRangeC: [10, 30],
    storageRhRangePct: [50, 65],
    indicativeShelfLifeDays: ref(180, 'src-demo'),
    properties: {
      moistureContentPct: 11,
      ph: 6.4,
      fatPct: 1.9,
      proteinPct: 12,
      waterActivity: 0.55,
      oxygenSensitivity: 1,
      moistureSensitivity: 5,
      lightSensitivity: 0,
      temperatureSensitivity: 1,
    },
    valuePerKgInr: ref(26),
    notes: 'Bulk commodity; moisture control dominant.',
    sourceIds: ['src-demo'],
  },
  {
    id: 'pulses',
    name: 'Pulses (split/whole)',
    category: 'pulse',
    form: 'processed',
    typicalStorageEnv: 'ambient',
    storageTempRangeC: [10, 30],
    storageRhRangePct: [50, 65],
    indicativeShelfLifeDays: ref(180, 'src-demo'),
    properties: {
      moistureContentPct: 11,
      ph: 6.5,
      fatPct: 1.5,
      proteinPct: 22,
      waterActivity: 0.55,
      oxygenSensitivity: 2,
      moistureSensitivity: 5,
      lightSensitivity: 1,
      temperatureSensitivity: 1,
    },
    valuePerKgInr: ref(80),
    notes: 'Rancidity and infestation managed via barrier + hermeticity.',
    sourceIds: ['src-demo'],
  },
  {
    id: 'spices',
    name: 'Ground spices',
    category: 'spice',
    form: 'processed',
    typicalStorageEnv: 'ambient',
    storageTempRangeC: [10, 30],
    storageRhRangePct: [45, 65],
    indicativeShelfLifeDays: ref(365, 'src-demo'),
    properties: {
      moistureContentPct: 8,
      ph: 5.8,
      fatPct: 8,
      proteinPct: 12,
      waterActivity: 0.45,
      oxygenSensitivity: 4,
      moistureSensitivity: 4,
      lightSensitivity: 4,
      temperatureSensitivity: 1,
    },
    valuePerKgInr: ref(300),
    notes: 'Volatile loss, oxidation and moisture caking drive packaging needs.',
    sourceIds: ['src-demo'],
  },
  {
    id: 'biscuits',
    name: 'Biscuits',
    category: 'bakery',
    form: 'processed',
    typicalStorageEnv: 'ambient',
    storageTempRangeC: [15, 28],
    storageRhRangePct: [40, 60],
    indicativeShelfLifeDays: ref(90, 'src-demo'),
    properties: {
      moistureContentPct: 3,
      ph: 7,
      fatPct: 18,
      proteinPct: 7,
      waterActivity: 0.3,
      oxygenSensitivity: 4,
      moistureSensitivity: 5,
      lightSensitivity: 2,
      temperatureSensitivity: 1,
    },
    valuePerKgInr: ref(200),
    notes: 'Low-aw product: moisture pickup causes texture loss; fat oxidation risk.',
    sourceIds: ['src-demo'],
  },
  {
    id: 'snacks',
    name: 'Fried snack products',
    category: 'snack',
    form: 'processed',
    typicalStorageEnv: 'ambient',
    storageTempRangeC: [15, 28],
    storageRhRangePct: [40, 60],
    indicativeShelfLifeDays: ref(60, 'src-demo'),
    properties: {
      moistureContentPct: 2,
      ph: 6.8,
      fatPct: 30,
      proteinPct: 6,
      waterActivity: 0.25,
      oxygenSensitivity: 5,
      moistureSensitivity: 5,
      lightSensitivity: 3,
      temperatureSensitivity: 1,
    },
    valuePerKgInr: ref(240),
    notes: 'Oxidation-dominant shelf-life limiter; needs high O2 barrier + light protection.',
    sourceIds: ['src-demo'],
  },
];

export const MATERIALS: PackagingMaterial[] = [
  {
    id: 'ldpe',
    name: 'LDPE film (low-density polyethylene)',
    category: 'plastic',
    otrCm3M2Day: ref(4500, 'src-film-data'),
    wvtrGm2Day: ref(18, 'src-film-data'),
    co2trCm3M2Day: ref(12000, 'src-film-data'),
    thicknessUmRange: [30, 100],
    sealable: true,
    tensileStrengthMpa: ref(18, 'src-film-data'),
    tempRangeC: [-30, 80],
    moistureBarrier: 0.7,
    oxygenBarrier: 0.05,
    lightBarrier: 0.1,
    recyclability: 'widely',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.28, 'src-lca'),
    costInrPerM2: ref(3.5),
    foodContactSafe: true,
    mapSuitable: false,
    advantages: ['Heat-sealable', 'Flexible, economical', 'Widely recyclable (PE stream)'],
    limitations: ['Very poor oxygen barrier', 'Not suitable for high-aw or high-fat products alone'],
    typicalApplications: ['Fresh produce bags', 'Overwrap', 'Inner liners'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
  {
    id: 'hdpe',
    name: 'HDPE film (high-density polyethylene)',
    category: 'plastic',
    otrCm3M2Day: ref(2200, 'src-film-data'),
    wvtrGm2Day: ref(9, 'src-film-data'),
    co2trCm3M2Day: ref(7000, 'src-film-data'),
    thicknessUmRange: [40, 120],
    sealable: true,
    tensileStrengthMpa: ref(26, 'src-film-data'),
    tempRangeC: [-30, 90],
    moistureBarrier: 0.8,
    oxygenBarrier: 0.08,
    lightBarrier: 0.15,
    recyclability: 'widely',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.3, 'src-lca'),
    costInrPerM2: ref(4),
    foodContactSafe: true,
    mapSuitable: false,
    advantages: ['Stiffer than LDPE', 'Better moisture barrier', 'Recyclable'],
    limitations: ['Oxygen barrier still poor', 'Cloudier'],
    typicalApplications: ['Cereal liners', 'Bulk sacks', 'Milk pouches'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
  {
    id: 'pet',
    name: 'PET film (polyester, BOPET)',
    category: 'plastic',
    otrCm3M2Day: ref(70, 'src-film-data'),
    wvtrGm2Day: ref(30, 'src-film-data'),
    co2trCm3M2Day: ref(250, 'src-film-data'),
    thicknessUmRange: [12, 36],
    sealable: false,
    tensileStrengthMpa: ref(200, 'src-film-data'),
    tempRangeC: [-70, 150],
    moistureBarrier: 0.55,
    oxygenBarrier: 0.75,
    lightBarrier: 0.2,
    recyclability: 'limited',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.6, 'src-lca'),
    costInrPerM2: ref(9),
    foodContactSafe: true,
    mapSuitable: true,
    advantages: ['Good O2 barrier', 'High strength', 'Wide temperature range'],
    limitations: ['Not heat-sealable alone (needs sealant layer)', 'Moderate moisture barrier'],
    typicalApplications: ['Lidding', 'Laminate outer layer', 'Vacuum bags'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
  {
    id: 'pp',
    name: 'PP film (polypropylene, BOPP)',
    category: 'plastic',
    otrCm3M2Day: ref(1600, 'src-film-data'),
    wvtrGm2Day: ref(6, 'src-film-data'),
    co2trCm3M2Day: ref(4500, 'src-film-data'),
    thicknessUmRange: [15, 50],
    sealable: true,
    tensileStrengthMpa: ref(140, 'src-film-data'),
    tempRangeC: [-20, 120],
    moistureBarrier: 0.85,
    oxygenBarrier: 0.2,
    lightBarrier: 0.15,
    recyclability: 'widely',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.35, 'src-lca'),
    costInrPerM2: ref(5),
    foodContactSafe: true,
    mapSuitable: false,
    advantages: ['Excellent moisture barrier', 'Good clarity and stiffness', 'Heat-sealable'],
    limitations: ['Moderate O2 barrier', 'Low-temperature brittleness'],
    typicalApplications: ['Snack films', 'Bakery overwrap', 'Labels'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
  {
    id: 'pla',
    name: 'PLA film (polylactic acid bioplastic)',
    category: 'bioplastic',
    otrCm3M2Day: ref(800, 'src-film-data'),
    wvtrGm2Day: ref(45, 'src-film-data'),
    co2trCm3M2Day: ref(2000, 'src-film-data'),
    thicknessUmRange: [20, 60],
    sealable: true,
    tensileStrengthMpa: ref(70, 'src-film-data'),
    tempRangeC: [-10, 55],
    moistureBarrier: 0.4,
    oxygenBarrier: 0.45,
    lightBarrier: 0.2,
    recyclability: 'rare',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.22, 'src-lca'),
    costInrPerM2: ref(10),
    foodContactSafe: true,
    mapSuitable: false,
    advantages: ['Bio-based', 'Industrially compostable', 'Good clarity'],
    limitations: ['Poor moisture barrier', 'Low heat tolerance', 'Composting infrastructure limited in India'],
    typicalApplications: ['Fresh produce trays', 'Cold-service overwrap'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
  {
    id: 'paper',
    name: 'Paper-based packaging (kraft, food-grade)',
    category: 'paper',
    otrCm3M2Day: ref(15000, 'src-film-data'),
    wvtrGm2Day: ref(400, 'src-film-data'),
    co2trCm3M2Day: ref(40000, 'src-film-data'),
    thicknessUmRange: [60, 300],
    sealable: false,
    tensileStrengthMpa: ref(30, 'src-film-data'),
    tempRangeC: [-20, 120],
    moistureBarrier: 0.1,
    oxygenBarrier: 0.02,
    lightBarrier: 0.85,
    recyclability: 'widely',
    recycledContentPct: 40,
    carbonKgCo2ePerM2: ref(0.18, 'src-lca'),
    costInrPerM2: ref(4.5),
    foodContactSafe: true,
    mapSuitable: false,
    advantages: ['Renewable, recyclable', 'Good light block', 'Consumer-preferred'],
    limitations: ['Minimal moisture barrier unless coated', 'Not hermetic'],
    typicalApplications: ['Outer cartons', 'Flour/sugar bags', 'Produce boxes'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
  {
    id: 'foil-lam',
    name: 'Aluminium foil laminate (PET/foil/PE)',
    category: 'foil-laminate',
    otrCm3M2Day: ref(0.5, 'src-film-data'),
    wvtrGm2Day: ref(0.2, 'src-film-data'),
    co2trCm3M2Day: ref(1, 'src-film-data'),
    thicknessUmRange: [60, 120],
    sealable: true,
    tensileStrengthMpa: ref(80, 'src-film-data'),
    tempRangeC: [-50, 120],
    moistureBarrier: 1,
    oxygenBarrier: 1,
    lightBarrier: 1,
    recyclability: 'rare',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.95, 'src-lca'),
    costInrPerM2: ref(18),
    foodContactSafe: true,
    mapSuitable: true,
    advantages: ['Near-total barrier to O2, moisture, light', 'Retort-capable'],
    limitations: ['High cost', 'Difficult to recycle', 'High carbon impact'],
    typicalApplications: ['Spice sachets', 'Retort pouches', 'Long-shelf-life snacks'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
  {
    id: 'met-pet',
    name: 'Metallized PET laminate (MET-PET/PE)',
    category: 'metallized',
    otrCm3M2Day: ref(2, 'src-film-data'),
    wvtrGm2Day: ref(1.5, 'src-film-data'),
    co2trCm3M2Day: ref(4, 'src-film-data'),
    thicknessUmRange: [30, 80],
    sealable: true,
    tensileStrengthMpa: ref(90, 'src-film-data'),
    tempRangeC: [-40, 110],
    moistureBarrier: 0.95,
    oxygenBarrier: 0.95,
    lightBarrier: 0.97,
    recyclability: 'limited',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.7, 'src-lca'),
    costInrPerM2: ref(12),
    foodContactSafe: true,
    mapSuitable: true,
    advantages: ['Near-foil barrier at lower cost', 'Excellent light block'],
    limitations: ['Recycling limited', 'Opaque'],
    typicalApplications: ['Snack pouches', 'Spice packs', 'Powder beverages'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
  {
    id: 'multi-3layer',
    name: 'Multilayer polymer laminate (PET/PP 3-layer)',
    category: 'multilayer',
    otrCm3M2Day: ref(45, 'src-film-data'),
    wvtrGm2Day: ref(4, 'src-film-data'),
    co2trCm3M2Day: ref(140, 'src-film-data'),
    thicknessUmRange: [50, 100],
    sealable: true,
    tensileStrengthMpa: ref(120, 'src-film-data'),
    tempRangeC: [-30, 120],
    moistureBarrier: 0.9,
    oxygenBarrier: 0.82,
    lightBarrier: 0.3,
    recyclability: 'limited',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.62, 'src-lca'),
    costInrPerM2: ref(11),
    foodContactSafe: true,
    mapSuitable: true,
    advantages: ['Balanced O2/moisture barrier', 'Printable, durable'],
    limitations: ['Multilayer recycling difficulty'],
    typicalApplications: ['Processed food pouches', 'Bulk milk powder'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
  {
    id: 'micro-perf-pp',
    name: 'Micro-perforated PP film',
    category: 'microperforated',
    otrCm3M2Day: ref(60000, 'src-film-data'),
    wvtrGm2Day: ref(350, 'src-film-data'),
    co2trCm3M2Day: ref(90000, 'src-film-data'),
    thicknessUmRange: [20, 30],
    sealable: true,
    tensileStrengthMpa: ref(120, 'src-film-data'),
    tempRangeC: [-20, 100],
    moistureBarrier: 0.35,
    oxygenBarrier: 0.01,
    lightBarrier: 0.15,
    recyclability: 'widely',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.36, 'src-lca'),
    costInrPerM2: ref(6.5),
    foodContactSafe: true,
    mapSuitable: true,
    advantages: ['High gas exchange for high-respiring produce', 'Reduces condensation risk vs solid film'],
    limitations: ['No oxygen barrier', 'Exchange rate fixed by perforation design'],
    typicalApplications: ['Salad/leafy bags', 'High-respiration produce MAP'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
  {
    id: 'biodeg-starch',
    name: 'Biodegradable starch-blend film',
    category: 'compostable',
    otrCm3M2Day: ref(2500, 'src-film-data'),
    wvtrGm2Day: ref(90, 'src-film-data'),
    co2trCm3M2Day: ref(7000, 'src-film-data'),
    thicknessUmRange: [30, 70],
    sealable: true,
    tensileStrengthMpa: ref(35, 'src-film-data'),
    tempRangeC: [-10, 60],
    moistureBarrier: 0.35,
    oxygenBarrier: 0.2,
    lightBarrier: 0.2,
    recyclability: 'not',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.2, 'src-lca'),
    costInrPerM2: ref(9.5),
    foodContactSafe: true,
    mapSuitable: false,
    advantages: ['Compostable under industrial conditions', 'Bio-based content'],
    limitations: ['Moderate barriers', 'Composting infrastructure limited'],
    typicalApplications: ['Produce bags', 'Dry-food overwrap'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
  // ——— Materials added for the Complete Packaging Solution upgrade ———
  // Rigid/glass/metal/woven categories (industry-typical demo values).
  {
    id: 'glass',
    name: 'Glass (jar/bottle)',
    category: 'glass',
    otrCm3M2Day: ref(0, 'src-film-data'),
    wvtrGm2Day: ref(0, 'src-film-data'),
    co2trCm3M2Day: ref(0, 'src-film-data'),
    thicknessUmRange: [2000, 8000],
    sealable: false,
    tensileStrengthMpa: ref(50, 'src-demo'),
    tempRangeC: [-40, 300],
    moistureBarrier: 1,
    oxygenBarrier: 1,
    lightBarrier: 0.6,
    recyclability: 'widely',
    recycledContentPct: 0.3,
    carbonKgCo2ePerM2: ref(1.4, 'src-lca'),
    costInrPerM2: ref(25),
    foodContactSafe: true,
    mapSuitable: true,
    advantages: ['Near-perfect barrier', 'Inert', 'Premium perception', 'Infinitely recyclable'],
    limitations: ['Heavy — transport cost', 'Breakage risk', 'Not for respiring produce unless vented'],
    typicalApplications: ['Jars', 'Bottles'],
    sourceIds: ['src-demo'],
    dataStatus: 'reference',
  },
  {
    id: 'aluminium',
    name: 'Aluminium (can/foil rigid)',
    category: 'metal',
    otrCm3M2Day: ref(0, 'src-film-data'),
    wvtrGm2Day: ref(0, 'src-film-data'),
    co2trCm3M2Day: ref(0, 'src-film-data'),
    thicknessUmRange: [50, 500],
    sealable: false,
    tensileStrengthMpa: ref(120, 'src-demo'),
    tempRangeC: [-40, 250],
    moistureBarrier: 1,
    oxygenBarrier: 1,
    lightBarrier: 1,
    recyclability: 'widely',
    recycledContentPct: 0.4,
    carbonKgCo2ePerM2: ref(1.8, 'src-lca'),
    costInrPerM2: ref(30),
    foodContactSafe: true,
    mapSuitable: true,
    advantages: ['Full barrier', 'Lighter than glass', 'High-value recycling stream'],
    limitations: ['Not for respiring produce', 'Forming energy high'],
    typicalApplications: ['Cans', 'Tins', 'Rigid foil trays'],
    sourceIds: ['src-demo'],
    dataStatus: 'reference',
  },
  {
    id: 'steel',
    name: 'Tinplate steel (can)',
    category: 'metal',
    otrCm3M2Day: ref(0, 'src-film-data'),
    wvtrGm2Day: ref(0, 'src-film-data'),
    co2trCm3M2Day: ref(0, 'src-film-data'),
    thicknessUmRange: [150, 500],
    sealable: false,
    tensileStrengthMpa: ref(300, 'src-demo'),
    tempRangeC: [-40, 250],
    moistureBarrier: 1,
    oxygenBarrier: 1,
    lightBarrier: 1,
    recyclability: 'widely',
    recycledContentPct: 0.25,
    carbonKgCo2ePerM2: ref(2.2, 'src-lca'),
    costInrPerM2: ref(22),
    foodContactSafe: true,
    mapSuitable: true,
    advantages: ['Hermetic + retort-capable', 'Very strong', 'Magnetic sorting aids recycling'],
    limitations: ['Heavy', 'Corrosion needs lacquer', 'Not for respiring produce'],
    typicalApplications: ['Food cans', 'Oil tins', 'Drums'],
    sourceIds: ['src-demo'],
    dataStatus: 'reference',
  },
  {
    id: 'jute',
    name: 'Jute sacking (natural fibre)',
    category: 'natural',
    otrCm3M2Day: ref(3000, 'src-demo'),
    wvtrGm2Day: ref(800, 'src-demo'),
    co2trCm3M2Day: ref(8000, 'src-demo'),
    thicknessUmRange: [500, 1500],
    sealable: false,
    tensileStrengthMpa: ref(40, 'src-demo'),
    tempRangeC: [-20, 80],
    moistureBarrier: 0.1,
    oxygenBarrier: 0.05,
    lightBarrier: 0.3,
    recyclability: 'widely',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.1, 'src-lca'),
    costInrPerM2: ref(6),
    foodContactSafe: true,
    mapSuitable: false,
    advantages: ['Biodegradable', 'Reusable', 'Traditional bulk trade'],
    limitations: ['No moisture barrier', 'Odour transfer possible', 'Needs liner for hygroscopic foods'],
    typicalApplications: ['Grain sacks', 'Pulse sacks'],
    sourceIds: ['src-demo'],
    dataStatus: 'reference',
  },
  {
    id: 'pa',
    name: 'Polyamide film (PA/nylon)',
    category: 'plastic',
    otrCm3M2Day: ref(8, 'src-film-data'),
    wvtrGm2Day: ref(30, 'src-film-data'),
    co2trCm3M2Day: ref(25, 'src-film-data'),
    thicknessUmRange: [15, 80],
    sealable: false,
    tensileStrengthMpa: ref(80, 'src-film-data'),
    tempRangeC: [-40, 120],
    moistureBarrier: 0.4,
    oxygenBarrier: 0.9,
    lightBarrier: 0.2,
    recyclability: 'limited',
    recycledContentPct: 0,
    carbonKgCo2ePerM2: ref(0.9, 'src-lca'),
    costInrPerM2: ref(14),
    foodContactSafe: true,
    mapSuitable: true,
    advantages: ['Excellent O₂ barrier for a film', 'Very strong, puncture resistant', 'Vacuum-packing standard'],
    limitations: ['Needs PE seal layer', 'Moisture-sensitive barrier performance'],
    typicalApplications: ['Vacuum pouches', 'Cheese/meat lamination'],
    sourceIds: ['src-film-data'],
    dataStatus: 'reference',
  },
];

export const DEFAULT_WEIGHTS = {
  foodCompatibility: 0.2,
  otrSuitability: 0.15,
  wvtrSuitability: 0.15,
  thicknessSuitability: 0.05,
  sealability: 0.05,
  temperatureCompatibility: 0.1,
  shelfLifeCapability: 0.1,
  costScore: 0.08,
  sustainabilityScore: 0.07,
  transportScore: 0.05,
};
